<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyTakeOut.Common\SkyTakeOut.Common.csproj" />
    <ProjectReference Include="..\SkyTakeOut.Core\SkyTakeOut.Core.csproj" />
    <ProjectReference Include="..\SkyTakeOut.EntityFrameworkCore\SkyTakeOut.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
